name: Deploy to Railway

on:
  push:
    branches: 
      -main
    tags:
      -v1.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
    # For posting a rich message using Block Kit
          payload: |
            { 
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "GDipSA 55CI/CD Assignment Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name*\n Xu Bingxin"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Metriculation:*\nA0265087W"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Email:*\n e1045762@u.nus.edu"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n https://github.com/Celia-Hsu-114/CICD-Assignment.git"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployment:*\n https://abandoned-interest-production.up.railway.app/"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://abandoned-interest-production.up.railway.app/>"
                  }
                }
              ]
            }

      
        env:
         SLACK_WEBHOOK_URL:  ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
